#!/bin/bash

set -e

payload=$(mktemp /tmp/bundle-test)
cat > $payload <&0

source_url=$(jq -r '.source.source_url' < $payload)
credentials=$(jq -r '.source.credentials' < $payload)

bundle config ${source_url} ${credentials}
