#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

echo "This is the destination"
echo ${destination}

payload=$(mktemp /tmp/bundle-test.XXXXXX)
cat > ${payload} <&0

echo "This is the payload"
cat ${payload}

source_url=$(jq -r '.source.source_url' < ${payload})
credentials=$(jq -r '.source.credentials' < ${payload})

echo "Executing bundle config"
bundle config --local ${source_url} ${credentials}

echo "Making directory"
mkdir ${destination}/.bundle

echo "Copying config file"
cp ".bundle/config" ${destination}/.bundle

echo "Outputting blank json"
echo "{\"version\":{}}" >&3

